insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Ursulina', 'Betje', 'ubetje0@shutterfly.com', '474 457 4114', 'eliska', '2022-12-19', 'asdf', '5516836/5499', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Daisy', 'Scintsbury', 'dscintsbury1@eventbrite.com', '206 529 8248', 'dscintsbury1', '2024-11-02', 'EO80*Dp@d}', '8271523/4472', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Kalinda', 'Denniss', 'kdenniss2@google.de', '125 844 5082', 'kdenniss2', '2024-02-11', '!lHHm!n3', '1871487/4726', 2, 30);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Erek', 'Stoakes', 'estoakes3@icio.us', '400 181 5692', 'estoakes3', '2023-05-16', '(vJzD8}xcoq''', '0815735/8080', 1, 23);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Dane', 'Yukhin', 'dyukhin4@wordpress.com', '695 351 3156', 'dyukhin4', '2023-09-17', '1mB4nX,L.{''_', '2749548/3353', 2, 35);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Rutherford', 'Ferenczy', 'rferenczy5@nature.com', '177 378 0196', 'rferenczy5', '2022-12-09', 'k0t0!a', '6330134/1365', 1, 31);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Dawna', 'Joscelyn', 'djoscelyn6@scientificamerican.com', '454 651 1844', 'djoscelyn6', '2024-03-20', '1aG?8aE$>G', '3435086/7277', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Nowell', 'Dimmer', 'ndimmer7@adobe.com', '804 679 9642', 'ndimmer7', '2023-07-30', 'Nmrn0&Ikgi', '8322530/3851', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Tildi', 'Howse', 'thowse8@blogs.com', '811 142 3487', 'thowse8', '2023-07-14', 'l!xq=@a', '7066403/6692', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Blondelle', 'Fost', 'bfost9@ocn.ne.jp', '758 185 4441', 'bfost9', '2024-09-15', '=l3Ml5', '6116338/4879', 1, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Dusty', 'Robbey', 'drobbeya@toplist.cz', '136 160 3785', 'drobbeya', '2024-10-05', 'P&DLBDi', '0716985/9955', 1, 40);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Dix', 'Mearing', 'dmearingb@eepurl.com', '693 624 2514', 'dmearingb', '2024-03-24', '<N&b.4KFQYN', '5640181/2129', 1, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Cort', 'Pass', 'cpassc@tmall.com', '834 581 4840', 'cpassc', '2024-11-12', 'LJW#$W', '7224887/7318', 2, 50);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Cassandra', 'Griffiths', 'cgriffithsd@blinklist.com', '547 298 7319', 'cgriffithsd', '2024-03-27', '+RtaB<beT~K', '5403938/8233', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Cull', 'Robertsson', 'crobertssone@wp.com', '630 429 2435', 'crobertssone', '2024-10-07', '7f2LH''?4', '5802233/7521', 3, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Wendye', 'Massie', 'wmassief@qq.com', '890 179 6502', 'wmassief', '2023-12-01', '+fQN''9olhF.', '8188420/0670', 1, 48);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Farley', 'Shard', 'fshardg@twitter.com', '233 633 6304', 'fshardg', '2023-07-01', 'byGOMuPP(', '0728755/1162', 1, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Foss', 'Ricardet', 'fricardeth@state.gov', '877 249 0968', 'fricardeth', '2023-10-27', 'g\bJ73}VoN', '0601307/9543', 3, 2);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Nicolas', 'Josephs', 'njosephsi@posterous.com', '925 974 2403', 'njosephsi', '2024-07-13', 'dZ)j`i`9ROC', '0207381/0361', 3, 32);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Kain', 'Cicchetto', 'kcicchettoj@hubpages.com', '558 836 8917', 'kcicchettoj', '2023-08-30', 'nJ?RZjwJT#', '6365250/7149', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Jonas', 'Lightwing', 'jlightwingk@4shared.com', '661 940 5314', 'jlightwingk', '2023-12-06', 'TpQB$6Vmli', '6967324/8547', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Gert', 'Biddlestone', 'gbiddlestonel@go.com', '392 555 7493', 'gbiddlestonel', '2024-04-16', '1O~A\VE*K', '4294002/1192', 3, 18);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Trstram', 'Claxson', 'tclaxsonm@paypal.com', '859 836 0868', 'tclaxsonm', '2024-01-21', 'rwFTd|p9&Kh', '0635904/8562', 3, 4);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Zane', 'Bedford', 'zbedfordn@scribd.com', '508 707 1711', 'zbedfordn', '2024-04-10', 'n_sJK`dQ3k', '6061674/3500', 3, 30);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Ines', 'Jotham', 'ijothamo@nature.com', '927 128 0024', 'ijothamo', '2024-10-21', 'z>3"~CB9?t', '3748509/4253', 3, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Aguste', 'Prujean', 'aprujeanp@blogtalkradio.com', '731 418 1681', 'aprujeanp', '2024-11-05', '(9Wz|L|u|jV@', '6284076/8941', 1, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Ninetta', 'Darley', 'ndarleyq@netlog.com', '991 834 1311', 'ndarleyq', '2024-03-30', 'Dh`)4mb@)B}', '5096778/2228', 3, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Zelig', 'Cathery', 'zcatheryr@yellowbook.com', '919 606 7435', 'zcatheryr', '2023-06-22', 'YSoGT4', '0696670/8763', 1, 20);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Giffie', 'Terzi', 'gterzis@sakura.ne.jp', '517 919 1835', 'gterzis', '2024-08-28', 'PF}SU1}Kf(FV', '8768568/7594', 2, 49);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Yard', 'Glossop', 'yglossopt@cam.ac.uk', '631 234 7954', 'yglossopt', '2024-10-09', 'xV\j{09"WPRR', '3334536/5408', 3, 3);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Niven', 'Quickenden', 'nquickendenu@ezinearticles.com', '408 679 2059', 'nquickendenu', '2023-04-27', 'eup)xz', '7844320/8836', 1, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Cindi', 'Pledger', 'cpledgerv@dot.gov', '538 707 3296', 'cpledgerv', '2023-12-15', '1ANqLg&f', '6375979/4512', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Rooney', 'Scholey', 'rscholeyw@stanford.edu', '314 398 3675', 'rscholeyw', '2024-07-18', '*k7~eJFdm\1_', '3255382/4261', 3, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Vasilis', 'Hannond', 'vhannondx@nytimes.com', '305 853 7926', 'vhannondx', '2024-02-19', 'g`ap&uT35CU', '0512036/2802', 3, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Hamel', 'Scouller', 'hscoullery@techcrunch.com', '511 270 2439', 'hscoullery', '2023-05-19', 'oQD/mUoY<''', '0582480/7268', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Krystal', 'Reeve', 'kreevez@skype.com', '344 992 8575', 'kreevez', '2023-12-16', '4Y8Al4<EpQ', '9546403/1965', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Dela', 'Van der Beken', 'dvanderbeken10@hc360.com', '105 341 4110', 'dvanderbeken10', '2023-06-09', '&<)|SYP\J', '5342436/7249', 1, 41);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Moyna', 'Treswell', 'mtreswell11@jimdo.com', '841 257 9824', 'mtreswell11', '2024-07-26', 'ocj777i,s', '2967861/8170', 2, 42);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Constantin', 'Bachelar', 'cbachelar12@istockphoto.com', '323 610 5853', 'cbachelar12', '2024-12-06', '7l*Z#$', '5992791/0761', 2, 7);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Fionnula', 'Clubley', 'fclubley13@nhs.uk', '550 411 4178', 'fclubley13', '2024-11-14', 'Po#6Xeec/DYn', '4412270/2017', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Burch', 'Killeley', 'bkilleley14@huffingtonpost.com', '401 533 7946', 'bkilleley14', '2024-01-27', '_@==oXju<', '5978612/9394', 2, 18);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Parrnell', 'Sutworth', 'psutworth15@squidoo.com', '829 928 8274', 'psutworth15', '2023-10-08', 'LQCt0OB@x?tW', '7132654/5208', 2, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Damara', 'Strettell', 'dstrettell16@soundcloud.com', '685 769 4268', 'dstrettell16', '2023-01-20', '<h&U}e)U7', '5720317/7768', 2, 15);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Bordie', 'MacGall', 'bmacgall17@comsenz.com', '771 872 3219', 'bmacgall17', '2024-03-04', '}vS,,FHjko', '7228214/5602', 1, 18);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Tally', 'Velden', 'tvelden18@sbwire.com', '693 251 8154', 'tvelden18', '2023-05-08', 'rcl9t`4pp`', '4807252/9657', 1, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Rebecka', 'Kemitt', 'rkemitt19@trellian.com', '614 620 8486', 'rkemitt19', '2023-12-10', '.uIH\0\*u', '9011510/6552', 1, 5);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Joycelin', 'Piel', 'jpiel1a@dedecms.com', '760 290 2977', 'jpiel1a', '2024-08-03', '.za7"{YA,m', '5739979/3730', 1, 44);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Skell', 'MacBrearty', 'smacbrearty1b@whitehouse.gov', '312 100 8502', 'smacbrearty1b', '2024-09-06', 'E,L,1v~g=', '1181302/8088', 2, 16);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Margy', 'Sellen', 'msellen1c@alibaba.com', '202 456 3123', 'msellen1c', '2023-05-04', '"qTRM/0', '6007759/1210', 1, null);
insert into USERS (FName, LName, Email, PhoneNum, NickName, LastLogon, Passwrd, BAN, ID_UserType, ID_Address) values ('Albrecht', 'Dolby', 'adolby1d@boston.com', '675 750 8156', 'adolby1d', '2023-05-29', '8LT=w0B', '9796218/5110', 1, null);

insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cat0.png', 'No cat image');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat1.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat2.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat3.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat4.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat5.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat6.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat7.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat8.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat9.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat10.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat11.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat12.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat13.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat14.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat15.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat16.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat17.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat18.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat19.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat20.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat21.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat22.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat23.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat24.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat25.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat26.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat27.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat28.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat29.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat30.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat31.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat32.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat33.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat34.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat35.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat36.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat37.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat38.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat39.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat40.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat41.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat42.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat43.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat44.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat45.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat46.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat47.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat48.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat49.jpeg', 'This cat is awsome!');
insert into POST_MEDIA (FILEPATH, TITLE) values ('/images/cats/cat50.jpeg', 'This cat is awsome!');


INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Moje kočka právě usnula v květináči, je to malý komik.', '2022-07-18', 1234, 6, 1);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Můj kocour dnes konečně chytil svou první hračku!', '2023-01-04', 115, 1, 2);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Neuvěříte, jak moje kočka umí otevřít dveře!', '2021-09-30', 884, 1, 3);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dneska mi kočka přinesla ponožku jako dárek. ❤️', '2022-12-21', 1420, 1, 4);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Naše Micka umí sedět jako člověk, koukněte na fotku!', '2024-03-11', 743, 18, 5);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Kocour právě shodil všechny květiny z parapetu... opět.', '2021-06-06', 980, 23, 6);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Moje kočka dneska celou dobu spala na klávesnici.', '2023-04-23', 453, 5, 7);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Zase si lehla přímo doprostřed puzzle. 🧩🐱', '2022-10-19', 1057, 17, 8);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Nemůžu uvěřit, jak naše kočka umí napodobit ptáky.', '2023-08-01', 302, 21, 9);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dneska si kočka sedla přímo do dortu. 🙈', '2021-03-14', 1265, 12, 10);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Máme nového kotěcího přítele – seznamte se s Mufem!', '2022-05-09', 677, 15, 11);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Můj kocour si oblíbil kaktus jako pelíšek. Au!', '2023-02-28', 138, 25, 12);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Naše kočka ráno mě probudila jemným ťukáním na čelo.', '2024-01-13', 1933, 2, 13);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dnes poprvé sněžilo a naše kočka to z okna sledovala fascinovaně.', '2021-12-01', 865, 30, 14);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Včera jsme zkusili dát kočce šátek a byla nadšená!', '2022-08-16', 602, 9, 15);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Maličký Čenda dneska poprvé zamňoukal nahlas!', '2023-07-07', 499, 13, 16);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Z kočky se stal šéf gauče, nikdo tam nesmí sedět kromě ní.', '2024-04-02', 1743, 19, 17);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Mám podezření, že moje kočka je ve skutečnosti pes.', '2022-02-20', 332, 7, 18);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dnes mi kočka pomohla “přepsat” e-mail. Díky za překlepy!', '2023-05-05', 1972, 3, 19);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Kočka si vlezla do lednice. Vážně nevím, co hledala.', '2024-05-10', 146, 28, 20);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Každé ráno mě vítá její mňoukání. To je láska.', '2021-11-25', 1203, 10, 21);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Můj kocour dnes odmítl jíst, protože miska nebyla rovně.', '2023-10-15', 708, 26, 21);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Kočka se schovala do tašky a šla se mnou nakupovat.', '2022-09-03', 1345, 8, 22);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Zase si hraje se stínem... nekonečná zábava!', '2024-06-01', 198, 22, 23);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Když slyší otvírání konzervy, přiletí rychlostí blesku.', '2021-04-28', 1766, 20, 24);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Mám pocit, že moje kočka ví víc než já.', '2023-03-17', 125, 14, 25);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dneska mi kočka donesla listí jako dárek.', '2022-11-11', 888, 24, 26);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Kočka zkouší spát v každé krabici, co najde.', '2023-12-05', 456, 16, 27);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Začala se učit aportovat. Ano, vážně!', '2021-10-02', 1099, 29, 28);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Spí 20 hodin denně a přesto je pořád unavená. 😸', '2022-06-30', 1877, 6, 29);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Nejlepší společník do deštivých dnů.', '2024-07-12', 341, 3, 30);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Už si začala vyžadovat ranní mazlení.', '2023-09-20', 1598, 11, 31);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Když slyší bouřku, schová se pod peřinu se mnou.', '2021-08-08', 777, 12, 32);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Nechápu, jak může být tak elegantní i ve spánku.', '2024-02-24', 1320, 30, 33);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Zase se uložila do květináče. To je už posedlost.', '2022-03-14', 509, 19, 34);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Začala sledovat ptáky přes televizi. Vážně!', '2023-11-07', 1010, 17, 35);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dnes poprvé škrábala gauč... a pak si šla lehnout jako královna.', '2021-05-22', 1989, 13, 36);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Když se směju, přiběhne. Asi mě chce utišit.', '2022-01-18', 890, 8, 37);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Zkusila se vydávat za sochu. Skoro jí to vyšlo.', '2023-06-14', 234, 5, 38);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Každé ráno mě budí ťukáním na skříňku.', '2024-08-20', 1617, 2, 39);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dnes jsem ji našel spát v botě. Jak se tam vešla?', '2021-07-10', 321, 18, 40);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Naučila se sedět na ramenou jako papoušek.', '2022-04-04', 722, 26, 41);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Kočka dnes “pomáhala” při pečení. Mouka všude.', '2023-01-28', 1801, 20, 42);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Zamilovala se do plyšového medvídka.', '2024-03-29', 539, 15, 43);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Má nový zvyk sedět v umyvadle. 🤷‍♂️', '2021-02-11', 1189, 7, 44);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Kočka mi dnes “pomohla” složit prádlo. Díky za chlupy.', '2022-07-25', 674, 9, 45);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Její výraz, když vidí vysavač, je k nezaplacení.', '2023-08-30', 1920, 14, 46);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Když slyší zvuk obalu od pamlsku, je hned u mě.', '2024-10-05', 1448, 23, 47);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Můj kocour dnes konečně chytil svou první hračku!', '2023-01-04', 115, 1, 9);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Neuvěříte, jak moje kočka umí otevřít dveře!', '2021-09-30', 884, 1, 30);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User, ID_Postmedia) VALUES ('Dneska mi kočka přinesla ponožku jako dárek. ❤️', '2022-12-21', 1420, 1, 14);


